### ISSUE TITLE
learn now bug

### ISSUE THREAD

**Issue by mortii** [mortii/anki-morphs#137]
```
blocked main thread for 298ms:
  File "<string>", line 1, in <module>
  File "aqt", line 509, in run
  File "aqt", line 717, in _run
  File "aqt.browser.table.table", line 451, in _on_context_menu
  File "/home/neo/.local/share/Anki2/addons21/472573498/browser_utils.py", line 149, in run_learn_card_now
    mw.col.sched.reposition_new_cards(selected_cards, 0, 1, False, True)
  File "anki.scheduler.base", line 247, in reposition_new_cards
  File "anki._backend_generated", line 845, in sort_cards
  File "anki._backend", line 162, in _run_command

Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.taskman", line 106, in wrapped_done
  File "aqt.operations", line 260, in wrapped_done
  File "/home/neo/.local/share/Anki2/addons21/472573498/reviewing_utils.py", line 192, in _show_card
    mw.reviewer._initWeb()
  File "aqt.reviewer", line 349, in _initWeb
  File "aqt.reviewer", line 789, in _bottomHTML
AttributeError: 'NoneType' object has no attribute 'time_taken'
```

**Comment by mortii** [comment]
the card was still shown as expected. catch and ignore the error?

**Comment by mortii** [comment]
the 'is None' checks above where the error occurs are not very robust apparently. Using try catch is probably just a better approach.

**Comment by Vilhelm-Ian** [comment]
I remember HQ also had an error where a value was None after a is None check

**Comment by mortii** [comment]
@Vilhelm-Ian yeah, it's very weird. Hopefully the try catch clause takes care of it.
