### ISSUE TITLE
Add error message on file encoding exception (generators)

### ISSUE THREAD

**Issue by mortii** [mortii/anki-morphs#245]
Example stack trace:
```
Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.taskman", line 106, in wrapped_done
  File "aqt.operations", line 252, in wrapped_done
  File "/home/neo/.local/share/Anki2/addons21/472573498/generators_window.py", line 266, in _on_failure
    raise error
  File "concurrent.futures.thread", line 58, in run
  File "aqt.operations", line 242, in wrapped_op
  File "/home/neo/.local/share/Anki2/addons21/472573498/generators_window.py", line 296, in _background_generate_report
    self._generate_morph_occurrences_by_file()
  File "/home/neo/.local/share/Anki2/addons21/472573498/generators_window.py", line 364, in _generate_morph_occurrences_by_file
    generators_text_processing.create_file_morph_occurrences(
  File "/home/neo/.local/share/Anki2/addons21/472573498/generators_text_processing.py", line 43, in create_file_morph_occurrences
    for line in file:
  File "codecs", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 5234: invalid continuation byte
```

Related issues: #232 #243

**Comment by aleksejrs** [comment]
Add an error message *with a file name*.
