### ISSUE TITLE
Anki encounters a problem when generating readability report or a study plan

### ISSUE THREAD

**Issue by IncontinentCell** [mortii/anki-morphs#266]
### Describe the bug

Anki encounters a problem when generating readability report or a study plan. It worked fine in the 2.2.5.

### Steps to reproduce the behavior

1. Go to Generators
2. Go to pick a folder with text data
3. Click "Generate Readability Report" or "Generate Study Plan"

[//]: # (Example:)
[//]: # (1. Go to '...')
[//]: # (2. Click on '....')
[//]: # (3. Scroll down to '....')
[//]: # (4. See error)

### Screenshots

![image](https://github.com/user-attachments/assets/9b4567b1-07b6-45f3-a9db-05227b9001fb)

### My system

[//]: # (Note: the AnkiMorphs version is found on the bottom of the AnkiMorphs settings window)

[//]: # (Example:)
[//]: # (- Operating System: Windows 11)
[//]: # (- Anki Version: 23.12.1)
[//]: # (- AnkiMorphs Version: v2.0.0)

 - Operating System: Windows 10
 - Anki Version:
 - AnkiMorphs Version: Happened both on 3.0.0-testing-2 and 3.0.0-testing-3 

### Additional context

This is the traceback from the debug info when generating readability report

Anki 24.06.2 (33a92379)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.19045

Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.taskman", line 106, in wrapped_done
  File "aqt.operations", line 252, in wrapped_done
  File "C:\Users\X\AppData\Roaming\Anki2\addons21\ankimorphs\generators\generators_window.py", line 261, in _on_failure
    raise error
  File "concurrent.futures.thread", line 58, in run
  File "aqt.operations", line 242, in wrapped_op
  File "C:\Users\X\AppData\Roaming\Anki2\addons21\ankimorphs\generators\generators_window.py", line 309, in _background_generate_report
    self._populate_tables_with_report(morph_occurrences_by_file)
  File "C:\Users\X\AppData\Roaming\Anki2\addons21\ankimorphs\generators\generators_window.py", line 411, in _populate_tables_with_report
    file_morphs_stats = readability_report_utils.get_morph_stats_from_file(
  File "C:\Users\X\AppData\Roaming\Anki2\addons21\ankimorphs\generators\readability_report_utils.py", line 54, in get_morph_stats_from_file
    highest_learning_interval: int | None = am_db.get_highest_learning_interval(
  File "C:\Users\X\AppData\Roaming\Anki2\addons21\ankimorphs\ankimorphs_db.py", line 330, in get_highest_learning_interval
    highest_learning_interval = self.con.execute(
sqlite3.OperationalError: no such column: highest_learning_interval

This is the traceback from the debug info when generating the study plan

Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.taskman", line 106, in wrapped_done
  File "aqt.operations", line 252, in wrapped_done
  File "C:\Users\X\AppData\Roaming\Anki2\addons21\ankimorphs\generators\generators_window.py", line 261, in _on_failure
    raise error
  File "concurrent.futures.thread", line 58, in run
  File "aqt.operations", line 242, in wrapped_op
  File "C:\Users\X\AppData\Roaming\Anki2\addons21\ankimorphs\generators\generators_window.py", line 708, in <lambda>
    op=lambda _: self._background_generate_study_plan(selected_output_options),
  File "C:\Users\X\AppData\Roaming\Anki2\addons21\ankimorphs\generators\generators_window.py", line 721, in _background_generate_study_plan
    self._generate_morph_occurrences_by_file(sorted_by_table=True)
  File "C:\Users\X\AppData\Roaming\Anki2\addons21\ankimorphs\generators\generators_window.py", line 342, in _generate_morph_occurrences_by_file
    sorted_input_files = self._get_input_files_table_sorted()
  File "C:\Users\X\AppData\Roaming\Anki2\addons21\ankimorphs\generators\generators_window.py", line 386, in _get_input_files_table_sorted
    file_name_text: str = file_name_item.text()
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by mortii** [comment]
Oh right, I fixed that a while ago, so it won't be in the final v3 release that comes out on friday. I do expect that release to have a trillion bugs though, so please let me know if you find any :pray: 

Thanks!
