### ISSUE TITLE
PermissionError when recalcing while priority file open in another program

### ISSUE THREAD

**Issue by mdraves91** [mortii/anki-morphs#285]
### Describe the bug

I had my priority file open in LibreOffice Calc and clicked Recalc in Anki, and got a PermissionError.

### Steps to reproduce the behavior

1. Create a priority file using the AnkiMorph generator
2. In AnkiMorphs note filters settings, set a notetype to use that priority file
3. Open the priority file csv in another program
4. Click Recalc in Anki

### Anki error output
```
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.19045

Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.taskman", line 106, in wrapped_done
  File "aqt.operations", line 252, in wrapped_done
  File "C:\Users\me\AppData\Roaming\Anki2\addons21\472573498\recalc\recalc_main.py", line 519, in _on_failure
    raise error
  File "concurrent.futures.thread", line 58, in run
  File "aqt.operations", line 242, in wrapped_op
  File "C:\Users\me\AppData\Roaming\Anki2\addons21\472573498\recalc\recalc_main.py", line 84, in <lambda>
    op=lambda _: _recalc_background_op(
  File "C:\Users\me\AppData\Roaming\Anki2\addons21\472573498\recalc\recalc_main.py", line 157, in _recalc_background_op
    _update_cards_and_notes(am_config, modify_enabled_config_filters)
  File "C:\Users\me\AppData\Roaming\Anki2\addons21\472573498\recalc\recalc_main.py", line 185, in _update_cards_and_notes
    morph_priorities: dict[tuple[str, str], int] = get_morph_priority(
  File "C:\Users\me\AppData\Roaming\Anki2\addons21\472573498\morph_priority_utils.py", line 63, in get_morph_priority
    return _load_morph_priorities_from_file(
  File "C:\Users\me\AppData\Roaming\Anki2\addons21\472573498\morph_priority_utils.py", line 80, in _load_morph_priorities_from_file
    with open(priority_file_path, mode="r+", encoding="utf-8") as csvfile:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\me\\AppData\\Roaming\\Anki2\\User 1\\priority-files\\beast-player-1-2.csv'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AJT Card Management ['1021636467', 2024-03-15T20:51, 'None', '']
AnkiConnect ['2055492159', 2024-07-25T23:55, 'None', '']
AnkiMorphs ['472573498', 2024-08-24T15:07, 'None', mod]
FSRS Helper Postpone  Advance  Load Balance  Easy Days  Disperse Siblings ['759844606', 2024-08-18T21:05, 'None', mod]
Japanese Support ['3918629684', 2023-10-18T22:13, 'None', '']
Jisho Support ['1262434132', 2021-05-14T13:27, 'None', '']
KanjiTable2 ['kanjitable2', 0, 'None', '']
MecabUnidic ['MecabUnidic', 0, 'None', '']
Progress Graphs and Stats for Learned and Matured Cards ['266436365', 2020-03-29T01:26, 'None', '']
ankimorphs-japanese-mecab ['1974309724', 2024-03-21T06:40, 'None', '']

===IDs of active AnkiWeb add-ons===
1021636467 1262434132 1974309724 2055492159 266436365 3918629684 472573498 759844606

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AJT Mortician ['1255924302', 2023-11-02T21:51, 'None', mod]
Anki Dojo ['433778282', 2024-06-22T03:21, 'None', '']
AnkiWebView Inspector ['31746032', 2023-06-27T14:26, 'None', '']
JPDB Anki Importer ['541896873', 2023-03-01T22:01, 'None', '']
Kanji Grid Kuuube ['1610304449', 2024-08-20T20:00, 'None', '']
LPCG LyricsPoetry Cloze Generator ['2084557901', 2023-12-06T21:43, 'None', '']
ankimorphs ['ankimorphs', 0, 'None', mod]
```

### My AnkiMorphs settings

```
{
    "algorithm_all_morphs_target_difference_weight": 10,
    "algorithm_all_morphs_target_distance": 1,
    "algorithm_average_priority_all_morphs": 0,
    "algorithm_average_priority_all_morphs_weight": 0,
    "algorithm_average_priority_learning_morphs_weight": 0,
    "algorithm_inflection_priority": false,
    "algorithm_learning_morphs_target_difference_weight": 10,
    "algorithm_learning_morphs_target_distance": 5,
    "algorithm_lemma_priority": true,
    "algorithm_lower_target_all_morphs": 4,
    "algorithm_lower_target_all_morphs_coefficient_a": 0.0,
    "algorithm_lower_target_all_morphs_coefficient_b": 1.0,
    "algorithm_lower_target_all_morphs_coefficient_c": 0.0,
    "algorithm_lower_target_learning_morphs": 1,
    "algorithm_lower_target_learning_morphs_coefficient_a": 1.0,
    "algorithm_lower_target_learning_morphs_coefficient_b": 0.0,
    "algorithm_lower_target_learning_morphs_coefficient_c": 0.0,
    "algorithm_total_priority_all_morphs": 1,
    "algorithm_total_priority_all_morphs_weight": 1,
    "algorithm_total_priority_learning_morphs_weight": 10,
    "algorithm_total_priority_unknown_morphs": 10,
    "algorithm_total_priority_unknown_morphs_weight": 10,
    "algorithm_upper_target_all_morphs": 6,
    "algorithm_upper_target_all_morphs_coefficient_a": 1.0,
    "algorithm_upper_target_all_morphs_coefficient_b": 0.0,
    "algorithm_upper_target_all_morphs_coefficient_c": 0.0,
    "algorithm_upper_target_learning_morphs": 2,
    "algorithm_upper_target_learning_morphs_coefficient_a": 1.0,
    "algorithm_upper_target_learning_morphs_coefficient_b": 0.0,
    "algorithm_upper_target_learning_morphs_coefficient_c": 0.0,
    "evaluate_morph_inflection": false,
    "evaluate_morph_lemma": true,
    "extra_fields_display_inflections": false,
    "extra_fields_display_lemmas": true,
    "filters": [
        {
            "extra_all_morphs": false,
            "extra_all_morphs_count": false,
            "extra_highlighted": false,
            "extra_score": false,
            "extra_score_terms": false,
            "extra_study_morphs": false,
            "extra_unknown_morphs": false,
            "extra_unknown_morphs_count": false,
            "field": "Expression",
            "modify": false,
            "morph_priority_selection": "Collection frequency",
            "morphemizer_description": "spaCy: ja_core_news_lg",
            "note_type": "Japanese (recognition)",
            "read": true,
            "tags": {
                "exclude": [],
                "include": []
            }
        },
        {
            "extra_all_morphs": false,
            "extra_all_morphs_count": false,
            "extra_highlighted": false,
            "extra_score": false,
            "extra_score_terms": false,
            "extra_study_morphs": false,
            "extra_unknown_morphs": false,
            "extra_unknown_morphs_count": false,
            "field": "Japanese",
            "modify": false,
            "morph_priority_selection": "Collection frequency",
            "morphemizer_description": "spaCy: ja_core_news_lg",
            "note_type": "A Dictionary of Japanese Grammar",
            "read": true,
            "tags": {
                "exclude": [],
                "include": []
            }
        },
        {
            "extra_all_morphs": false,
            "extra_all_morphs_count": false,
            "extra_highlighted": true,
            "extra_score": false,
            "extra_score_terms": false,
            "extra_study_morphs": true,
            "extra_unknown_morphs": true,
            "extra_unknown_morphs_count": true,
            "field": "Expression",
            "modify": true,
            "morph_priority_selection": "beast-player-1-2.csv",
            "morphemizer_description": "spaCy: ja_core_news_lg",
            "note_type": "Japanese Morphman Audio Ankiweb",
            "read": true,
            "tags": {
                "exclude": [],
                "include": []
            }
        },
        {
            "extra_all_morphs": false,
            "extra_all_morphs_count": false,
            "extra_highlighted": true,
            "extra_score": false,
            "extra_score_terms": false,
            "extra_study_morphs": true,
            "extra_unknown_morphs": true,
            "extra_unknown_morphs_count": true,
            "field": "Reading",
            "modify": true,
            "morph_priority_selection": "beast-player-1-2.csv",
            "morphemizer_description": "spaCy: ja_core_news_lg",
            "note_type": "Japanese Morphman",
            "read": true,
            "tags": {
                "exclude": [],
                "include": []
            }
        }
    ],
    "hide_inflection_toolbar": false,
    "hide_lemma_toolbar": false,
    "hide_recalc_toolbar": false,
    "interval_for_known_morphs": 21,
    "preprocess_ignore_bracket_contents": true,
    "preprocess_ignore_names_morphemizer": false,
    "preprocess_ignore_names_textfile": true,
    "preprocess_ignore_round_bracket_contents": false,
    "preprocess_ignore_slim_round_bracket_contents": false,
    "preprocess_ignore_suspended_cards_content": false,
    "read_known_morphs_folder": false,
    "recalc_due_offset": 500000,
    "recalc_interval_for_known": 21,
    "recalc_move_known_new_cards_to_the_end": false,
    "recalc_number_of_morphs_to_offset": 100,
    "recalc_offset_new_cards": false,
    "recalc_on_sync": false,
    "recalc_read_known_morphs_folder": false,
    "recalc_suspend_known_new_cards": true,
    "recalc_toolbar_stats_use_known": false,
    "recalc_toolbar_stats_use_seen": true,
    "recalc_unknowns_field_shows_inflections": true,
    "recalc_unknowns_field_shows_lemmas": false,
    "shortcut_browse_all_same_unknown": "Shift+L",
    "shortcut_browse_ready_same_unknown": "L",
    "shortcut_browse_ready_same_unknown_lemma": "Ctrl+Shift+L",
    "shortcut_generators": "Ctrl+Shift+G",
    "shortcut_known_morphs_exporter": "Ctrl+Shift+E",
    "shortcut_learn_now": "Ctrl+Alt+N",
    "shortcut_progression": "Ctrl+Alt+P",
    "shortcut_recalc": "Ctrl+M",
    "shortcut_set_known_and_skip": "K",
    "shortcut_settings": "Ctrl+O",
    "shortcut_view_morphemes": "Ctrl+Alt+V",
    "skip_only_known_morphs_cards": true,
    "skip_show_num_of_skipped_cards": true,
    "skip_unknown_morph_seen_today_cards": true,
    "tag_fresh": "am-fresh-morphs",
    "tag_known_automatically": "am-known-automatically",
    "tag_known_manually": "am-known-manually",
    "tag_learn_card_now": "am-learn-card-now",
    "tag_not_ready": "am-not-ready",
    "tag_ready": "am-ready",
    "toolbar_stats_use_known": false,
    "toolbar_stats_use_seen": true
}
```

### My system

 - Operating System: Windows-10-10.0.19045
 - Anki Version: Anki 24.06.3 (d678e393)  (ao)
 - AnkiMorphs Version: 3.1.0

### Additional context

This is obviously easy to work around, by closing other programs with the priority file open. 
From the error message I can see the file is being opened in r+ mode, which also allows writing to the file. I'm not sure why the addon would need to write to the priority file when doing a recalc, so it may be better to change this to "r". Or if not, catch and handle the PermissionError.

**Comment by mortii** [comment]
Thanks for the detailed report! I'm not able to reproduce it however, neither on windows or ubuntu... Could you edit the line in `\472573498\morph_priority_utils.py` to use `r` instead of `r+` and see if that fixes it?

**Comment by mortii** [comment]
Pushed the change in [v3.1.1](https://github.com/mortii/anki-morphs/releases/tag/v3.1.1). 

Hopefully it will fix the problem, if not, let me know!

**Comment by mdraves91** [comment]
That fixed it, thanks!
