### ISSUE TITLE
Another Error while reviewing

### ISSUE THREAD

**Issue by HQYang1979** [mortii/anki-morphs#89]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 23.10 (51a10f09) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: Windows-10-10.0.23595
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-12-06 21:29:45
Add-ons possibly involved: ⁨ankimorphs-alpha⁩

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons21\472573498\reviewing_utils.py", line 298, in <lambda>
    (key_skip.toString(), lambda: _set_card_as_known_and_skip(self, am_config)),
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons21\472573498\reviewing_utils.py", line 244, in _set_card_as_known_and_skip
    if self.card.type != CARD_TYPE_NEW:
AttributeError: 'NoneType' object has no attribute 'type'

**Comment by mortii** [comment]
@Vilhelm-Ian Very thorough, nicely done! I'm wondering if we can just gracefully catch the error and ignore it. When I got my error earlier today it didn't actually cause a problem other than the error pop-up window show up, I still saw the card in the review window like I wanted to...

**Comment by Vilhelm-Ian** [comment]
@mortii  for the self._showquestion() is just to put assert self.card is not None. That's easy. For what happened to hqyang I have no idea how it happened since there is assert just five lines above it. We can just do if self.card is not none and self.card.type != CARD_TYPE . But i have no idea if it would work since it already escaped an assert

**Comment by Vilhelm-Ian** [comment]
@mortii I think the issue atleast with the self._showquestion is not that the reviewer is destroyed it's that the reviewer calls the function .cleanup which makes the card property be None. And when we manually call the self._showQuestion method the method assumes that card is not none they don't bother checking. Since _showQuestion is a private method they assume we wouldn't be using it. I think even you do use mw.reviewer you will still have to assert mw.reviewer.card

**Comment by mortii** [comment]
> @mortii I think the issue atleast with the self._showquestion is not that the reviewer is destroyed it's that the reviewer calls the function .cleanup which makes the card property be None. And when we manually call the self._showQuestion method the method assumes that card is not none they don't bother checking. Since _showQuestion is a private method they assume we wouldn't be using it. I think even you do use mw.reviewer you will still have to assert mw.reviewer.card

Hmmm, possibly. My fix was just the lowest hanging fruit I could think of. If this error occurs again then we can dig deeper into this :+1:
